---
- hosts: localhost
  vars:
    image_rg_name: rgs
    location: east us  
    vm_name: Demo-VM
    resource_group: rgs3
    vm_disk_id: "/subscriptions/02ac19d2-71ae-471d-b697-97daef2db017/resourceGroups/RGS3/providers/Microsoft.Compute/disks/Demo-VM"

  tasks:
    - name: Create image rg
      azure_rm_resourcegroup:
       name: "{{ image_rg_name }}"
       location: "{{ location }}"
      register: rg
    - debug:
        var: rg

    - name: Stop and generalize VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        generalized: yes
  
    - name: Create an images from a VMs
      azure_rm_image:
        resource_group: "{{ image_rg_name }}"
        name: "image_{{ vm_name }}"
        source: "{{ vm_disk_id }}"
        os_type: Linux
