---
- hosts: localhost
  become: yes
  vars:
    resource_group: rgs3
    location: eastus
    profile_name: testtm

  tasks:
  - name: Create a Traffic Manager Profile
    azure_rm_trafficmanagerprofile:
      name: "{{ profile_name }}"
      resource_group: "{{ resource_group }}"
      location: global
      profile_status: enabled
      routing_method: performance
      dns_config:
        relative_name: tmtest
        ttl: 60
      monitor_config:
        protocol: HTTPS
        port: 80
        path: '/'
      tags:
        Environment: Poc

  # - name: create a endpoint for a traffic manager profile
  #   azure_rm_trafficmanagerendpoint:
  #       resource_group: "{{ resource_group }}"
  #       profile_name: "{{ profile_name }}"
  #       name: testendpoint1
  #       type: external_endpoints
  #       location: "{{ location }}"
  #       priority: 2
  #       weight: 1
  #       target: 1.2.3.4

